### ISSUE TITLE
Trouble with Blender 2.91.2

### ISSUE THREAD

**Issue by recaremo** [manahter/nCNC2#1]
Hi,
I'm so glad as I found your AddOn and I installed it at once.
I'm a blender use for many years an dhope you can help me.
I build my own CNC with Arduino Uno as Controller where GRBL 1.1 is installed. 

I got access with other programms to the machine (CNCjs) but in Blender I can't establishe a connection. I also test it with Blender 2.8.3

**Comment by manahter** [comment]
> Hi,
> I'm so glad as I found your AddOn and I installed it at once.
> I'm a blender use for many years an dhope you can help me.
> I build my own CNC with Arduino Uno as Controller where GRBL 1.1 is installed.
> 
> I got access with other programms to the machine (CNCjs) but in Blender I can't establishe a connection. I also test it with Blender 2.8.3

Hi,
First off, I assume you download the addon from here;
https://github.com/manahter/nCNC/releases

If you downloaded the codeButton in the picture, it will not work. 
![resim](https://user-images.githubusercontent.com/73780835/107921668-e3e69000-6f7f-11eb-9827-c5ad803cf879.png)


Since I am busy these days, I cannot spare much time for development. 
I'll test it for the Blender 2.9x at the first time I'm available.

**Comment by recaremo** [comment]
Thanks,

I'll test it soon.
teşekkür ederim

Frank

**Comment by recaremo** [comment]
Well I used Blender 2.83.12 and 2.91.2 and download the last release. 
In Blender 2.83.12 I don't see the feature -SHOW

In Blender 2.91.2 I can see it. I can convert to G-Code and Export the file. (That file works fine with CNCjs)
But I can't select a port, there is only the: "Select the machine" - but nothing more.

Well, take so much time you need for your other work. I can wait.

**Comment by manahter** [comment]
> Well I used Blender 2.83.12 and 2.91.2 and download the last release.
> In Blender 2.83.12 I don't see the feature -SHOW
> 
> In Blender 2.91.2 I can see it. I can convert to G-Code and Export the file. (That file works fine with CNCjs)
> But I can't select a port, there is only the: "Select the machine" - but nothing more.
> 
> Well, take so much time you need for your other work. I can wait.

I've tested version 2.83.12 now. I did not see a problem. What do you mean by 'SHOW'?

I tested version 2.91.2 as well. I did not find any problems.
Possible reasons for the problem may be:

1) Your machine connection remained open in another program. So the nCNC plug-in cannot see the machine.

2) I'm testing them on Linux. They haven't been tested yet on Windows or Mac.

NOTE: Remember that only one program can be connected to the machine at a time.

If you can share the problem in more detail, maybe we can find a solution.
For example, if you can share images, code outputs, etc., let's do a review later.

**Comment by manahter** [comment]
>2.83.12
![2-83-12](https://user-images.githubusercontent.com/73780835/108059402-81b48a80-7066-11eb-8ffd-99ab73194e0b.jpg)
>2.91.2
![2-91-2](https://user-images.githubusercontent.com/73780835/108059407-837e4e00-7066-11eb-9795-ec139e1e5d08.jpg)

**Comment by recaremo** [comment]
OK. I can only the PlugIn in Windows and on a Mac. Might be thats the problem. As soon as possible I wil install an Linux System and check it again.

**Comment by manahter** [comment]
If you know Turkish, you can write Turkish after that.
I just don't recommend you install Linux for this add-on. Because the add-on is not yet professional. Will develop over time.

**Comment by recaremo** [comment]
Sorry, but my Turkish is not good enough for conversation.
Well, hope it works soon with windows. 
Because I'm a technic freak I'll test it with Linux too. I already planed to use a Linux System - so why not!
You did a good work - and I hope I can support it. I wrote already something about it in a german maker-forum.

**Comment by manahter** [comment]
> Sorry, but my Turkish is not good enough for conversation.

Okay it does not matter.

> Well, hope it works soon with windows.

I'll test for Windows for a day in the future.  But not very recently. I will do that when the plugin becomes a little more professional.

> Because I'm a technic freak I'll test it with Linux too. I already planed to use a Linux System - so why not!

After spending some time in Linux, it gets more beautiful.

> You did a good work - and I hope I can support it. I wrote already something about it in a german maker-forum.

Thank you.
Development continues.
