### ISSUE TITLE
windows 10 com connection blender 2.92 steam edition

### ISSUE THREAD

**Issue by alexanderdfox** [manahter/nCNC2#4]
windows 10 com connection blender 2.92 steam edition

not listing com ports. com3 is active over usb
![Screenshot 2021-05-03 012210](https://user-images.githubusercontent.com/21992452/116846512-09159280-abae-11eb-9230-4c9018376087.png)

"using Grbl 1.1g ['$' for help]" Arduino software connects fine

**Comment by manahter** [comment]
I just tested on Linux.

Can you try this code on Blender Python Console in your system?

```
# Import the port scan module
from nCNC.modules.serial.tools.list_ports import comports

# Scan and return port list
comports()
```

Example my port list, only 1 device is connected:
![Ss](https://user-images.githubusercontent.com/73780835/116897270-bd122e80-ac3d-11eb-94b6-444c2f1b6f95.png)

**Comment by alexanderdfox** [comment]
I get this returned: [<nCNC.modules.serial.tools.list_ports_common.ListPortInfo object at 0x0000016DCA03BC08>]
but still can't connect

**Comment by manahter** [comment]
Can you try this code on Blender Python Console in your system?

```
# Print selected port
bpy.data.scenes['Scene'].ncnc_pr_connection.ports

# Print available ports
bpy.data.scenes['Scene'].ncnc_pr_connection.get_ports(C)
```
Example:
![Ekran Görüntüsü - 2021-05-06 14-04-56](https://user-images.githubusercontent.com/73780835/117288382-1cf21a80-ae74-11eb-8dfe-0184ef1a43f2.png)

**Comment by alexanderdfox** [comment]
![Screenshot 2021-05-08 021241](https://user-images.githubusercontent.com/21992452/117530463-ef57bf00-afa2-11eb-8de2-92e57db17b73.png)

Error:
TypeError: EnumProperty(...): expected a tuple containing (identifier, name, description) and optionally an icon name and unique number

**Comment by manahter** [comment]
I have made a slight correction in codes. Can you delete the plug-in and reinstall

**Comment by alexanderdfox** [comment]
Thank you... it connected and can move the cnc machine

**Comment by manahter** [comment]
I'm glad :)
Share again if other problems take out.
