### ISSUE TITLE
Can`t unlock my machine

### ISSUE THREAD

**Issue by chicosimoes** [manahter/nCNC2#5]
Even after re-configuring the parameters to be the same as the ones I use in other software, the addon does not unlock for movement. As is expected to be done "homing" but does not obey any command.
Ps .: The machine works with other controllers normally.

I use 2.92 Blender on a linux.

**Comment by manahter** [comment]
Doesn't work only "homing" command. Others work?

**Comment by manahter** [comment]
The addon tests only GRBL v1.1
Can you share the image?

**Comment by chicosimoes** [comment]
I think this is the problem then. I'm using GRBLQ (https://github.com/LETARTARE/grblQ-Mega-4axes) adapted to run on an "Arduino Mega", it was based on GRBL v0.6.
I will get this question right on my set and report if I was successful.
Thank you and congratulations for the initiative!

**Comment by manahter** [comment]
I hope you success. Thanks.
